---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Introduction
    - name: module-02
      label: Installing Convert2RHEL
    - name: module-03
      label: Pre-conversion Analysis
    - name: module-04
      label: Running Convert2RHEL
    - name: module-05
      label: Completing the Conversion
tabs:
  - name: ">_ centos"
    port: 443
    path: /wetty
    user: root
    host: centos
    type: tty
