== What is Convert2RHEL

Convert2RHEL is a command line utility that allows for self-service
migration between RHEL-like distributions to officially supported Red
Hat Enterprise Linux instances.

The convert2rhel tool handles subscribing the target system to your Red
Hat customer account while maintaining customizations, configurations,
and workloads.

Convert2RHEL is also a supported operation which means if you run into
issues with the conversion process, you can open a ticket with Red Hat
Support.

Before you begin the installation process, verify that you are running
CentOS Linux and on the latest minor version.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
cat /etc/centos-release
----

.Output
[source,text]
----
cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
----

== Enabling the Convert2RHEL repository

The Convert2RHEL RPM is an offical Red Hat package. Therefore it is
readily availble from the Red Hat software repository (CDN). As your
CentOS server is not subscribed to the Red Hat CDN, you will need to
enable the Convert2RHEL repository.

First, you will pull down the GPG signing key:

[source,bash,subs="+macros,+attributes",role=execute]
----
curl -o /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release https://www.redhat.com/security/data/fd431d51.txt
----

Second, download the SSL certificate:

[source,bash,subs="+macros,+attributes",role=execute]
----
curl --create-dirs -o /etc/rhsm/ca/redhat-uep.pem https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem
----

Thirdly, download the convert2rhel repository file:

[source,bash,subs="+macros,+attributes",role=execute]
----
curl -o /etc/yum.repos.d/convert2rhel.repo https://ftp.redhat.com/redhat/convert2rhel/7/convert2rhel.repo
----
